### ISSUE TITLE
all-admin-users package

### ISSUE THREAD

**Issue by Konard** [deep-foundation/deep-packages#4]
This package should contain:
1. Handler to Install link (one time creation of join links to all users when package is installed), to make it possible join link should be created to `packages` user before this package is installed.
2. Sync handler on User insertion (Join link from that User instance to admin user) should be created.

5000 ₽ can be claimed as a reward. Reward will be paid to the first programmer that will make an NPM package that will pass review of @Konard

**Comment by konard** [comment]
Reward was claimed by @Lemeho
