### ISSUE TITLE
Warframe prime trash buyer

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deep-packages#79]
I need a deep package that generates messages to buy prime trash from people. You should use this library https://github.com/LiKissDmd/warframe-market-prime-trash-buyer or write your own

**Comment by LiKissDmd** [comment]
I take it

**Comment by LiKissDmd** [comment]
https://www.npmjs.com/package/@likissdmd/warframe-market-prime-trash-buyer-deep
Ready
